/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2012
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
package com.bravo.li.pojo;

import javax.persistence.*;

@Entity(name ="Human")
@Inheritance(strategy = InheritanceType.JOINED)
public class Human {
	
	@Id // @Id indicates that this it a unique primary key
    @GeneratedValue // @GeneratedValue indicates that value is automatically generated by the server
    private Long id;
	
	private Gender gender = Gender.FEMALE;
	private int age = 18;
	private String name;
	private double health = 120;
	
	@Transient
	private double curr_health;
	
	public Human() {
		
	}
	/**
	 * @param gender
	 * @param age
	 * @param name
	 * @param health
	 */
	public Human(Gender gender, int age, String name, double health) {
		super();
		this.gender = gender;
		this.age = age;
		this.name = name;
		this.health = health;
	}
	/**
	 * @return the gender
	 */
	@Enumerated(EnumType.STRING)
	public Gender getGender() {
		return gender;
	}
	/**
	 * @param gender the gender to set
	 */
	public void setGender(Gender gender) {
		this.gender = gender;
	}
	/**
	 * @return the age
	 */
	public int getAge() {
		return age;
	}
	/**
	 * @param age the age to set
	 */
	public void setAge(int age) {
		this.age = age;
	}
	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
	/**
	 * @return the health
	 */
	public double getHealth() {
		return health;
	}
	/**
	 * @param health the health to set
	 */
	public void setHealth(double health) {
		this.health = health;
	}
	/**
	 * @return the curr_health
	 */
	public double getCurr_health() {
		return curr_health;
	}
	/**
	 * @param curr_health the curr_health to set
	 */
	public void setCurr_health(double curr_health) {
		this.curr_health = curr_health;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Human [id=" + id + ", gender=" + gender + ", age=" + age
				+ ", name=" + name + ", health=" + health + "]";
	}
}
